### ISSUE TITLE
v1.2 bugfixes

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/rivine#530]
- [x] [ci build is broken](https://github.com/threefoldtech/rivine/issues/545)
- [ ] [coin outputs not always marked as spent in a multi-transaction block](https://github.com/threefoldtech/rivine/issues/526) 
- [x] [Forking fails if the blockstake output used for block creation is defined in the fork to switch to](https://github.com/threefoldtech/rivine/issues/523)
- [ ] [add timestamp and transaction order for explorer transaction](https://github.com/threefoldtech/rivine/issues/532)
- [ ] [Unencrypted wallets block api registration on startup ](https://github.com/threefoldtech/rivine/issues/522)
- [x] [Consensus set hangs when closing](https://github.com/threefoldtech/rivine/issues/543)
- [x] [1 of 3 block creators for goldchain is incomplete](https://github.com/threefoldtech/rivine/issues/546)
- [x] [Check for block creation transactions fails in case of a fork](https://github.com/threefoldtech/rivine/issues/523)

**Comment by GlenDC** [comment]
Going to close this issue and remove it form the project. As discussed a couple of weeks ago, we do not require this kind of aggregation issue. It created extra burden on the developers by needing to maintain this extra list of project-related issues, while it does not add anything extra (given that for a project you can already filter on labels, e.g. type_bug).
